-- Global game settings
PLAYER_SPEED = 3
PLAYER_R = 2
PLAYER_SLOW_SPEED = PLAYER_SPEED / 2

PLAYER_MAX_HP = 100
PLAYER_BULLET_SPEED = 6
PLAYER_BULLET_R = 2
PLAYER_BULLET_DMG = 27


POWERUP_R = 16
POWERUP_SPEED = 1
POWERUP_VALUE = 3
POWERUP_SCORE_MULTIPLIER = 1000

BOSS_R = 64
BOSS_MAX_HP = 1000000
BOSS_SPEED = 0.125

ENEMY_BULLET_R = 2
ENEMY_BULLET_SPEED = 2
ENEMY_BULLET_DMG = 10

CLOUD_SPEED = 1
CLOUD_R = 32

KEY_REPEAT = 200
KEY_DELAY= 10

-- OPTIONS MENU
MUSIC_ENABLED = true

-- DEV FEATURES
HITBOX_ENABLED = false 
FPS_ENABLED = false